# Generated by Django 4.2.4 on 2023-08-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onlineshop',
            table='advertisements',
        ),
    ]
